linters-settings:
  govet:
    enable:
      - shadow
      - fieldalignment
  revive:
    confidence: 0
  gocyclo:
    min-complexity: 31
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4

linters:
  enable:
    - revive
    - goimports
    - gosec
    - unparam
    - unconvert
    - predeclared
    - prealloc
    - misspell
    - govet

issues:
  exclude-rules:
    - path: bson.go
      text: "should be .*ObjectID"
      linters:
        - golint
        - stylecheck
